spring:
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.20.103:3306/dms_uat?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: dms01
    password: Cse@dms01
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect